create table todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task text check (char_length(task) > 3),
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table todos enable row level security;
create policy "Individuals can create todos." on todos for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own todos. " on todos for
    select using ((select auth.uid()) = user_id);
create policy "Individuals can update their own todos." on todos for
    update using ((select auth.uid()) = user_id);
create policy "Individuals can delete their own todos." on todos for
    delete using ((select auth.uid()) = user_id);


-- https://supabase.com/docs/guides/realtime/subscribing-to-database-changes#enable-postgres-changes
BEGIN;

DROP publication IF EXISTS supabase_realtime;

CREATE publication supabase_realtime;

COMMIT;

ALTER publication supabase_realtime ADD TABLE todos;


INSERT INTO storage.buckets(id,name) VALUES ('test-bucket','test-bucket');
INSERT INTO storage.buckets(id,name) VALUES ('another-bucket','another-bucket');

CREATE POLICY "Only allow access to authenticated users"
ON storage.objects
FOR ALL
TO authenticated
USING (bucket_id = 'test-bucket')
WITH CHECK (bucket_id = 'test-bucket');