BEGIN;

-- Create todos table if it doesn't exist
CREATE TABLE IF NOT EXISTS todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task text check (char_length(task) > 3),
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE IF EXISTS todos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Individuals can create todos" ON todos;
CREATE POLICY "Individuals can create todos" 
ON todos 
FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Individuals can view their own todos" ON todos;
CREATE POLICY "Individuals can view their own todos"
ON todos
FOR SELECT
USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "Individuals can update their own todos." ON todos;
CREATE POLICY "Individuals can update their own todos."
ON todos
FOR UPDATE
USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "Individuals can delete their own todos." ON todos;
CREATE POLICY "Individuals can delete their own todos."
ON todos
FOR DELETE
USING ((select auth.uid()) = user_id);

DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime;

ALTER PUBLICATION supabase_realtime ADD TABLE todos;

INSERT INTO storage.buckets (id, name)
VALUES ('test-bucket', 'test-bucket')
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Only allow access to authenticated users" ON storage.objects;

CREATE POLICY "Only allow access to authenticated users"
ON storage.objects
FOR ALL
TO authenticated
USING (bucket_id = 'test-bucket')
WITH CHECK (bucket_id = 'test-bucket');

COMMIT;