services:
  nginx:
    container_name: supabase-nginx
    image: jonasal/nginx-certbot:6.2.0-nginx1.31.3
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    depends_on:
      kong:
        condition: service_healthy
    volumes:
      - ./volumes/nginx:/etc/nginx/user_conf.d
      - ./volumes/nginx/letsencrypt:/etc/letsencrypt
    environment:
      PROXY_DOMAIN: ${PROXY_DOMAIN:?error}
      NGINX_PASS_FILE: /etc/nginx/user_conf.d/supabase-self-host-users
      NGINX_SNIPPETS_PATH: /etc/nginx/user_conf.d/snippets
      CERTBOT_EMAIL: your@email.org
    command:
      - /bin/bash
      - -c
      # https://www.baeldung.com/linux/nginx-config-environment-variables#4-a-common-pitfall
      - |
        echo "$${PROXY_AUTH_USERNAME}:$${PROXY_AUTH_PASSWORD}" > $${NGINX_PASS_FILE} \
        && cp /etc/nginx/user_conf.d/nginx.conf /tmp/nginx.tmp \
        && envsubst '$${PROXY_DOMAIN} $${NGINX_SNIPPETS_PATH} $${NGINX_PASS_FILE}' < /tmp/nginx.tmp > /etc/nginx/user_conf.d/nginx.conf \
        && /scripts/start_nginx_certbot.sh
