name: "Greet on issue open"

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Greet issue author
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const username = issue.user.login;
            const body = [
              `👋 Hey @${username}, thanks for opening an issue! I'll take a look as soon as I can.`,
              `In the meantime, if you'd like to support the project a ⭐ on the repo would mean a lot.\nYou can also support my work by [Buying me a coffee](${{vars.SPONSOR_URL}}).`
            ].join("\n\n");

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: body
            });
